import type { Metadata } from "next";
import { ThemeProvider } from "@/components/custom/theme-provider";
import { LanguageProvider } from "../contexts/LanguageContext";
import "./globals.css";

export const metadata: Metadata = {
  title: "{ Pxdro Code }",
  description: "Generated by Pxdro Code",
  icons: {
    icon: "/logo.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" suppressHydrationWarning>
      <body>
        <LanguageProvider>
          <ThemeProvider attribute="class" defaultTheme="light" enableSystem>
            {children}
          </ThemeProvider>
        </LanguageProvider>
      </body>
    </html>
  );
}