import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "{ Pxdro Code }",
  description: "Generated by Pxdro Code",
  icons: {
    icon: "/logo.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body>
        {children}
      </body>
    </html>
  );
}
